/// <reference lib="webworker" />
import { precacheAndRoute } from 'workbox-precaching';

declare const self: ServiceWorkerGlobalScope;

// Activate new service worker immediately (don't wait for all tabs to close)
self.addEventListener('install', () => {
  self.skipWaiting();
});
self.addEventListener('activate', (event) => {
  event.waitUntil(self.clients.claim());
});

// Precache all assets generated by Vite build
precacheAndRoute(self.__WB_MANIFEST);

// --- Push Notification Handler ---
self.addEventListener('push', (event) => {
  if (!event.data) return;

  let payload: { title?: string; body?: string; url?: string; tag?: string; chatId?: string };
  try {
    payload = event.data.json();
  } catch {
    payload = { title: 'RAG-Hybrid', body: event.data.text() };
  }

  // Extract chatId from url if present (e.g., "/?chat=chat_123")
  const url = payload.url || '/';
  let chatId = payload.chatId;
  if (!chatId && url.includes('chat=')) {
    const match = url.match(/[?&]chat=([^&]+)/);
    if (match) chatId = match[1];
  }

  const title = payload.title || 'RAG-Hybrid';
  const options: NotificationOptions & { actions?: Array<{ action: string; title: string }> } = {
    body: payload.body || '',
    icon: '/pwa-192x192.png',
    badge: '/pwa-192x192.png',
    tag: payload.tag || 'rag-notification',
    data: { url, chatId },
    actions: chatId
      ? [
          { action: 'view', title: 'View' },
          { action: 'dismiss', title: 'Dismiss' },
        ]
      : [],
  };

  event.waitUntil(self.registration.showNotification(title, options));
});

// --- Notification Click Handler ---
self.addEventListener('notificationclick', (event) => {
  event.notification.close();

  const data = event.notification.data || {};
  const url = (data.url as string) || '/';
  const chatId = data.chatId as string | undefined;

  // "Dismiss" action: delete the linked chat and close notification
  if (event.action === 'dismiss' && chatId) {
    event.waitUntil(
      fetch(`/api/v1/chats/${chatId}`, { method: 'DELETE' }).catch(() => {})
    );
    return;
  }

  // Default / "View" action: open or focus the app, then tell it which chat to load
  event.waitUntil(
    self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((windowClients) => {
      for (const client of windowClients) {
        if (client.url.includes(self.location.origin) && 'focus' in client) {
          // postMessage is more reliable than navigate() on mobile
          if (chatId) {
            client.postMessage({ type: 'LOAD_CHAT', chatId });
          }
          return (client as WindowClient).focus();
        }
      }
      // No existing window — open with URL param as fallback
      return self.clients.openWindow(chatId ? `/?chat=${chatId}` : url);
    })
  );
});
